create table if not exists public.mail_accounts (
  id uuid primary key,
  user_id uuid not null,
  provider text not null check (provider = 'gmail'),
  provider_account_id_hash text not null,
  last_history_id text,
  last_sync_at timestamptz,
  last_full_scan_at timestamptz,
  rules_version integer not null default 1,
  unique (user_id, provider_account_id_hash)
);

create table if not exists public.mail_context (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  account_id uuid not null references public.mail_accounts(id) on delete cascade,
  gmail_message_id text not null,
  gmail_thread_id text,
  source_fingerprint text not null,
  direction text,
  category text not null,
  importance_score real not null default 0,
  urgency_score real not null default 0,
  spam_score real not null default 0,
  phishing_score real not null default 0,
  malicious_score real not null default 0,
  financial_sensitivity_score real not null default 0,
  privacy_score real not null default 0,
  action_score real not null default 0,
  reply_score real not null default 0,
  work_score real not null default 0,
  calendar_score real not null default 0,
  confidence_score real not null default 0,
  requires_reply boolean not null default false,
  attention_allowed boolean not null default false,
  work_allowed boolean not null default false,
  calendar_allowed boolean not null default false,
  deadline_at timestamptz,
  context_ciphertext text,
  context_iv text,
  encryption_version integer,
  source_updated_at text,
  processed_at timestamptz not null default now(),
  classifier_version integer not null,
  unique (account_id, gmail_message_id)
);

create index if not exists mail_context_priority_idx
  on public.mail_context (account_id, attention_allowed, importance_score desc, urgency_score desc);

alter table public.mail_accounts enable row level security;
alter table public.mail_context enable row level security;

create policy "mail_accounts_select_own" on public.mail_accounts for select using (auth.uid() = user_id);
create policy "mail_accounts_insert_own" on public.mail_accounts for insert with check (auth.uid() = user_id);
create policy "mail_accounts_update_own" on public.mail_accounts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "mail_accounts_delete_own" on public.mail_accounts for delete using (auth.uid() = user_id);

create policy "mail_context_select_own" on public.mail_context for select using (auth.uid() = user_id);
create policy "mail_context_insert_own" on public.mail_context for insert with check (auth.uid() = user_id);
create policy "mail_context_update_own" on public.mail_context for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "mail_context_delete_own" on public.mail_context for delete using (auth.uid() = user_id);
