create table if not exists public.active_ui_context (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  account_id uuid not null references public.mail_accounts(id) on delete cascade,
  source_message_id text not null,
  source_thread_id text,
  source_fingerprint text not null,
  context_type text not null,
  status text not null default 'active',
  display_title text not null,
  sender_display text,
  summary text,
  importance_score real not null default 0,
  urgency_score real not null default 0,
  needs_attention boolean not null default false,
  requires_reply boolean not null default false,
  work_required boolean not null default false,
  calendar_required boolean not null default false,
  deadline_at timestamptz,
  work_job_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  classifier_version integer not null,
  unique (account_id, source_message_id)
);

create index if not exists active_ui_context_current_idx
  on public.active_ui_context (account_id, status, expires_at, importance_score desc, urgency_score desc);

create table if not exists public.active_work_state (
  job_id text primary key,
  user_id uuid not null,
  source_message_id text not null,
  source_thread_id text,
  clean_title text not null,
  status text not null,
  current_step text,
  task_summary text,
  deadline timestamptz,
  generated_reply text,
  approval_state text,
  gmail_draft_id text,
  artifact_metadata jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists active_work_state_user_idx
  on public.active_work_state (user_id, status, updated_at desc);

alter table public.active_ui_context enable row level security;
alter table public.active_work_state enable row level security;

create policy "active_ui_context_select_own" on public.active_ui_context for select using (auth.uid() = user_id);
create policy "active_ui_context_insert_own" on public.active_ui_context for insert with check (auth.uid() = user_id);
create policy "active_ui_context_update_own" on public.active_ui_context for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "active_ui_context_delete_own" on public.active_ui_context for delete using (auth.uid() = user_id);

create policy "active_work_state_select_own" on public.active_work_state for select using (auth.uid() = user_id);
create policy "active_work_state_insert_own" on public.active_work_state for insert with check (auth.uid() = user_id);
create policy "active_work_state_update_own" on public.active_work_state for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "active_work_state_delete_own" on public.active_work_state for delete using (auth.uid() = user_id);
